# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'bundler'
Bundler.require
require 'hop_hop'
require 'hop_hop/test'
require 'timecop'

HopHop::Event.sender=HopHop::TestSender.new
HopHop::Consumer.receiver=HopHop::TestReceiver.new

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run_excluding :rabbitmq
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
  
  config.before do
    HopHop::Event.sender.reset if HopHop::Event.sender.respond_to?(:reset)#throw away all events
    HopHop::Event.producer_prefix='localhost.9999'
  end
end
